"""empty message

Revision ID: 39fcf9818f9c
Revises: 303d9b14d2c0
Create Date: 2022-12-16 03:21:44.047858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39fcf9818f9c'
down_revision = '303d9b14d2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('people', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planets', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favoritos_name_key', type_='unique')
        batch_op.drop_constraint('favoritos_uid_key', type_='unique')
        batch_op.drop_constraint('favoritos_url_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['user'], ['email'])
        batch_op.create_foreign_key(None, 'planets', ['planets'], ['uid'])
        batch_op.create_foreign_key(None, 'people', ['people'], ['uid'])
        batch_op.drop_column('name')
        batch_op.drop_column('url')
        batch_op.drop_column('uid')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['uid'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uid')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uid')

    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('favoritos_url_key', ['url'])
        batch_op.create_unique_constraint('favoritos_uid_key', ['uid'])
        batch_op.create_unique_constraint('favoritos_name_key', ['name'])
        batch_op.drop_column('planets')
        batch_op.drop_column('people')
        batch_op.drop_column('user')

    # ### end Alembic commands ###
